name: main integration build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23.2'

    - name: Build
      run: go build -tags prd -v ./...

    - name: Test
      run: go test -tags prd -v ./...

    - name: Run coverage
      run: go test -cover -coverprofile=coverage.out -tags=prd ./...

    - name: Update coverage report
      uses: jonas-grgt/go-coverage-report@main
      with:
        coverage-file: coverage.out
      if: github.event_name == 'push'  
      continue-on-error: true
